### ISSUE TITLE
100% CPU usage with .findWordsWithSubsequence

### ISSUE THREAD

**Issue by 50Wliu** [atom/superstring#39]
In certain cases, it is possible for `findWordsWithSubsequence` to use 100% CPU.  Once this happens, CPU usage remains at 100% until Atom crashes.  I can't reproduce it anymore, but when it happened I could consistently reproduce with `console.log editorElement.getAttribute` in a CoffeeScript file and typing `console ` over and over again in a new plain text tab.  This persisted even after reloading Atom.

/cc @nathansobo

**Comment by nathansobo** [comment]
I narrowed it down to a file containing a very large source map string. It was transpiled from a TypeScript file in  `atom-languageclient`. I've posted the transpiled output [here](https://gist.github.com/nathansobo/4afe51420b2b75c8328f5793085c3818).

It looks like very long words could be problematic for our exhaustive search model, which I think has quadratic time complexity due to the growing list of match variants. I feel a bit silly for not asking myself, "what if we run this against a super long word?".

I think a reasonable solution could be to just limit the maximum number of characters we're willing to scan. We should be careful to scan at least enough characters to get the score for one subsequence variant.

Another approach could be constraining the number of match variants we examine by inserting them into some sort of priority queue and only preserving the top N. That might improve performance of the matching in general at the cost of computing the most accurate score in some cases.

/cc @leroix @maxbrunsfeld
