### ISSUE TITLE
Marker Index implementation

### ISSUE THREAD

**Issue by jessegrosjean** [atom/superstring#73]
I'm interested in the marker index implementation.

I think I understand the underlying tree structure. But using the internal tree nodes to track range start/end positions is new to me. It adds complexity, but I think saves on performance when adding/removing big spans that overlap many small spans.

My questions: 

1. Is this some well known strategy for tracking ranges? If so what's the original implementation?

2. Are you satisfied with the structure? Would you implemented it the same way again?

Thanks!

**Comment by rsese** [comment]
Hey @jessegrosjean, sorry for the delay - some maintainers are in the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638), I think that's probably a better place to get some feedback about these questions.  Someone might still jump in here but I think you'll get better response on Slack - going to close this out just to help keep the issues list as tidy as possible and since we use issues to do work tracking as much as possible.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
